version: "3.3"
services:
  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
    cap_add:
      - NET_ADMIN
    # required if Pi-hole is to provide DHCP
    # network_mode: "host"
    environment:
      # enter your docker host IP here
      ServerIP: 172.20.1.112
      # IPv6 Address if your network supports it
      #ServerIPv6: 
      # jwilder/proxy envs, see readme for more info
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.yourdomain.local
      VIRTUAL_PORT: 80
      TZ: "America/Indianapolis"
    # Add your own custom hostnames you need for your domain
    #extra_hosts:
      #   Point any of the jwilder virtual_host addresses
      # to your docker host ip address
      #  - 'pihole.yourdomain.local:192.168.1.101'
    volumes:
      - "pihole-etc-pihole:/etc/pihole"
      - "pihole-etc-dnsmasq-d:/etc/dnsmasq.d"
      # WARNING: if this log don't exist as a file on the host already
      # docker will try to create a directory in it's place making for lots of errors
      # - './data/log/pihole.log:/var/log/pihole.log'
    restart: always

volumes:
  pihole-etc-pihole:
  pihole-etc-dnsmasq-d:
