version: "3"
services:
  pihole:
    build: .
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - "pihole:/etc"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ='America/Indianapolis'
      - WEBPASSWORD="thats_just_personal_you_know"
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
    dns:
      - 127.0.0.1
      - 1.1.1.1

volumes:
  pihole:
